services:
  database:
    image: postgres:15
    container_name: casacue_db
    environment:
      POSTGRES_USER: casacue
      POSTGRES_PASSWORD: password
      POSTGRES_DB: casacue
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U casacue"]
      interval: 5s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    container_name: casacue_backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=casacue;Username=casacue;Password=password
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "5001:8080"
    command: >
      sh -c "./docker/scripts/wait-for-it.sh database:5432 -- 
             dotnet ef database update --project CasaCue &&
             dotnet CasaCue.dll"

  auth:
    build:
      context: .
      dockerfile: ./docker/auth/Dockerfile
    container_name: casacue_auth
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - JWT_Secret=mySuperSecretKeyForJWT123mySuperSecretKeyForJWT123
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=casacue;Username=casacue;Password=password
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "5003:8080"
    command: >
      sh -c "./docker/scripts/wait-for-it.sh database:5432 -- 
             dotnet ef database update --project CasaCue.Auth &&
             dotnet CasaCue.Auth.dll"

volumes:
  db_data:
