name: .NET CI and Test

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      JWT_SECRET: "mySuperSecretKeyForJWT123!@#$mySuperSecretKeyForJWT123!@#$"
      ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=casacue_db;Username=casacue;Password=password"

    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up .NET environment
      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x'

      # Start PostgreSQL as a Docker container
      - name: Start PostgreSQL service
        run: |
          docker run --name test-database -e POSTGRES_USER=casacue -e POSTGRES_PASSWORD=password -e POSTGRES_DB=casacue_db -p 5432:5432 -d postgres:15
        env:
          POSTGRES_USER: casacue
          POSTGRES_PASSWORD: password
          POSTGRES_DB: casacue_db

      # Wait for PostgreSQL to be ready
      - name: Wait for PostgreSQL to be ready
        run: |
          until docker exec test-database pg_isready -U casacue; do
            echo "Waiting for database to be ready..."
            sleep 5
          done
        shell: bash

      # Restore dependencies
      - name: Restore dependencies
        run: |
          dotnet restore CasaCue/CasaCue.csproj
          dotnet restore CasaCue.Tests/CasaCue.Tests.csproj

      # Apply EF migrations
      - name: Apply EF migrations
        run: dotnet ef database update --project CasaCue/CasaCue.csproj

      # Build the project
      - name: Build project
        run: dotnet build CasaCue/CasaCue.csproj --configuration Release --no-restore

      # Run tests
      - name: Run tests
        run: dotnet test CasaCue.Tests/CasaCue.Tests.csproj --no-restore --verbosity normal
