name: .NET CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore CasaCue/CasaCue.csproj

    - name: Build
      run: dotnet build CasaCue/CasaCue.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test CasaCue.Tests/CasaCue.Tests.csproj --no-restore --verbosity normal
